---
apiVersion: v1
kind: Service
metadata:
  name: agent-sandbox-webhook-service
  namespace: agent-sandbox-system
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app: agent-sandbox-controller
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: agent-sandbox-webhook
webhooks:
  - name: mutate-extensions-api-v1alpha1-sandboxclaim.kb.io
    clientConfig:
      service:
        name: agent-sandbox-webhook-service
        namespace: agent-sandbox-system
        path: "/mutate-extensions-api-v1alpha1-sandboxclaim"
      caBundle: Cg== # To be filled by script
    rules:
      - operations: ["CREATE"]
        apiGroups: ["extensions.agents.x-k8s.io"]
        apiVersions: ["v1alpha1"]
        resources: ["sandboxclaims"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
